# This workflow will install Python dependencies, build the package and then build the documentation.

name: Build documentation


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9.15
        channels: conda-forge,defaults
        channel-priority: strict
        show-channel-urls: true
        use-mamba: true
        environment-file: ci-env.yml
        activate-environment: deepdisc
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install 'git+https://github.com/facebookresearch/detectron2.git@80307d2d5e06f06a8a677cc2653f23a4c56402ac'
        pip install 'git+https://github.com/pmelchior/scarlet.git'
        pip install .[dev]
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
    - name: Install notebook requirements
      run: |
        sudo apt-get install pandoc
    - name: Build docs
      run: |
        sphinx-build -T -E -b html -d docs/build/doctrees ./docs docs/build/html
