# This workflow runs pre-commit hooks on pull requests to enforce coding style.
# To ensure correct configuration, please refer to:
#   https://lincc-ppt.readthedocs.io/en/latest/practices/ci_precommit.html

name: Run pre-commit hooks

on:
  pull_request:

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    env: 
      SKIP: "check-lincc-frameworks-template-version,pytest-check,no-commit-to-branch,validate-pyproject,check-added-large-files,sphinx-build"
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9.15
        channels: conda-forge,defaults
        channel-priority: strict
        show-channel-urls: true
        use-mamba: true
        environment-file: ci-env.yml
        activate-environment: deepdisc
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install 'git+https://github.com/facebookresearch/detectron2.git@80307d2d5e06f06a8a677cc2653f23a4c56402ac'
        pip install 'git+https://github.com/pmelchior/scarlet.git'
        pip install .[dev]
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()